// src/app/layout.js (貼り付け後の一例)

import { Inter } from 'next/font/google'
import './globals.css' // この行は残す

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App', // ここはプロジェクト名に変わっているかも
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* ここにFont Awesomeのlinkタグが追加される */}
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      />
      <body className={inter.className}>{children}</body>
    </html>
  )
}