// src/app/layout.js (変更後)

// import { Inter } from 'next/font/google' ← この行を削除
import './globals.css'

// const inter = Inter({ subsets: ['latin'] }) ← この行を削除

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossOrigin="anonymous"
        referrerPolicy="no-referrer"
      />
      <body>{children}</body> {/* ← ここを <body className={inter.className}>{children}</body> から変更 */}
    </html>
  )
}